### ISSUE TITLE
Reorganize db.py into db package and rename as sqlite_handler

### ISSUE THREAD

**Issue by kaestro** [tarto-dev/tagsy-discord#31]
I think a little bit of reorganizing the structure of project can be of help on improving readability and maintenance.

My first idea is creating db package for this can be of one big part.

If this is to be accepted, the next step I'm trying to do is creating

1. sqlite_setup.py which will set all the tables needed for the project to run
2. dockerfile which will install sqlite and set the directory on .env

What do  you think about it?

Also, I think some other python source code on the outermost most directory (e.g. bot.py, helper.py, config.py) needs to be moved moved into some other directory and organized.

**Comment by tarto-dev** [comment]
Yeah, the bot quickly gets complex while I was coding it. Some refactor & reorganization would be needed.
Although editing the database part may be an interesting move, we'll need to make it in two parts, first for reorganization, second for the database part as I'll have to edit server settings as well if I don't want data loss with migration.

> dockerfile which will install sqlite and set the directory on .env

Not sure what you mean there, as sqlite doesn't require install (that's why I picked it).
That says, I'm not sure if this is the best choice if the bot growth, so I've opened #29 to check it up, no clues so far on where I'll put data if I move out of sqlite


So far, I'm able to download and upload databases, so data migration won't be that hard, but we have to keep this in mind and limit as much we can with database structures modifications

**Comment by kaestro** [comment]
I think sqlite was an great idea to begin with for it's easy and ready to go.
Only thing I think we need to keep in mind is that to trying to keep scalability like using interfaces in java.
But it's of issue to consider on later time

**Comment by tarto-dev** [comment]
We definitively need for stability, and improving readability & maintenance is always a good thing, but yeah, related to database & Dockerfile, not sure the best moment to do (but, it will never be "the" moment as data will increase as bot is used.)

A data migration task will be needed for sure, let's fix what needs to and improve stability first, then we'll handle data! 

Still, thanks for your help on that boss, I'm opened to any suggestions about further commands (see existing idea through Issues, and please don't hesitate to add some)

**Comment by kaestro** [comment]
c072d1640ebcdc8954b7123b12c06d681f6359c6
